FROM apache/airflow:3.3.2

USER root

RUN apt-get update \
    && apt-get install -y \
        openjdk-17-jre-headless \
        curl \
        wget \
        procps \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow

RUN pip install --no-cache-dir \
    "apache-airflow-providers-fab==3.9.0" \
    pyspark==3.5.3 \
    pandas \
    numpy \
    faker \
    psycopg2-binary \
    sqlalchemy \
    snowflake-connector-python \
    dbt-core \
    dbt-snowflake \
    boto3 \
    pyarrow \
    s3fs

RUN mkdir -p /opt/airflow/jars \
    && wget -q https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar -O /opt/airflow/jars/hadoop-aws-3.3.4.jar \
    && wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar -O /opt/airflow/jars/aws-java-sdk-bundle-1.12.262.jar \
    && wget -q https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/1.0.7.Final/wildfly-openssl-1.0.7.Final.jar -O /opt/airflow/jars/wildfly-openssl-1.0.7.Final.jar

USER airflow